version: '3.7'
services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    networks:
      - db-network
  recipe-service:
    build: ./recipe-service
    container_name: recipe-service
    ports:
      - "8001:8001"
    networks:
      - db-network
  shared-voc-service:
    build: ./shared-voc-service
    container_name: shared-voc-service
    ports:
      - "8002:8002"
    networks:
      - db-network
  comments-service:
    build: ./comments-service
    container_name: comments-service
    ports:
      - "8003:8003"
    networks:
      - db-network
  fav-service:
    build: ./fav-service
    container_name: fav-service
    ports:
      - "8004:8004"
    networks:
      - db-network
  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "8005:8005"
    networks:
      - db-network
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: recipe_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: recipe_manager
    ports:
      - '5432:5432'
    networks:
      - db-network
    volumes:
      - my-db:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - db-network

# Names our volume
volumes:
  my-db:

networks:
  db-network:
    name: db-network
